### ISSUE TITLE
ItemNames

### ISSUE THREAD

**Issue by Protophim** [czp3009/GlobalMarket#1]
Plugins works nice. It is a bit uncomfy to write the complete item string. Is there a way to define some "easy to use names"? I tried to sell a welder but whatever I tried it didn't work.
![Unbenannt](https://user-images.githubusercontent.com/62715193/77677331-cf785e00-6f8f-11ea-9e32-b1ad6cab8de4.png)

**Comment by czp3009** [comment]
"Simple name" is the substring after "/".

For example, "Welderitem" is simple name of "MyObjectBuilder_PhysicalGunObject/Welderitem".

Just type this command to sell:

```
!market sell Welderitem 1 10
```

**Comment by czp3009** [comment]
Simple name is the substring after "/", but it's case sensitive.

For the example above, you should type "WelderItem" not "Welderitem".

I will check out if it's possible to allow case-insensitive item name in command, and update this plugin.

**Comment by czp3009** [comment]
https://github.com/czp3009/GlobalMarket/commit/4efd45590b79b84031632e59f50451c978f31c0b
