### ISSUE TITLE
BUG: cant buy things from market to cargo! all ways say no free storage.

### ISSUE THREAD

**Issue by dorimanx** [czp3009/GlobalMarket#2]
Hi,

There is an issue with buying large amount of things from market.
When i like to buy something small that can go to backpack all ok,

But when trying to use ray cast to point on my cargo, it's always say no room!
as it's never try to put it to cargo, or not detecting cargo.

Please check.

Thank you!

**Comment by czp3009** [comment]
Because this plugin only pick up the Cargo player facing, not all Cargo in the ship.

Due to plugin API limit, it's difficult to get roadmap of whole conveny system in a grid.

And another limit is that player must hold hand tool to facing a Cargo(until appear HUD highlight).

**Comment by dorimanx** [comment]
oo! didnt know that... so we must actually point at cargo port and highlight it and hold a tool...
OK... need to check that. if you can, please add this to plugin INFO...

Thanks.

**Comment by czp3009** [comment]
ok, i will add this to README
