### ISSUE TITLE
Item Name

### ISSUE THREAD

**Issue by q764995354** [czp3009/GlobalMarket#3]
I want to know what the name of the mine ingot is?
I tried many times and it was wrong！
For example, what is the name of the iron ingot?
Is Iron Ingot it?
Hope to tell me the names of various mine ingots. Thank you!

**Comment by czp3009** [comment]
follow README

![image](https://user-images.githubusercontent.com/17246126/105820331-653baa00-5ff4-11eb-8b44-e654b4b9811f.png)

Go further, it's possible to use short name of a item if no duplicate short name in inventory and cargo(e.g. iron ingot and iron ore), for example: !market sell iron, !market sell welderitem

https://github.com/czp3009/GlobalMarket/issues/1
